name: techcontrol
description: "A project for telecontrol"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  email_validator: ^3.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  internet_connection_checker: ^3.0.1
  dot_curved_bottom_nav: ^0.0.2
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.21
  file_picker: ^9.1.0
  image_picker: ^1.1.2
  flutter_speed_dial: ^7.0.0
  pinput: ^5.0.1
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  webview_flutter: ^4.10.0
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1

flutter_native_splash:

  color: "#222E50"
  image: "assets/images/write_techcontrol.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/icone1024.jpg"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#222E50"
  adaptive_icon_foreground: "assets/images/icone1024.jpg"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/lotties/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700